version: "3"
services:
  postgres-container:
    image: postgres-image:latest
    network_mode: bridge
    container_name: postgres-container
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
    restart: unless-stopped
  # APP*****************************************
  rest-app-container:
    image: rest-app-image:latest
    network_mode: bridge
    container_name: rest-app-container
    volumes:
      - c:/rest-app:/usr/local/tomcat/rest-app-data
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres-container
    links:
      - postgres-container